test

diff --git a/.github/workflows/preview.yaml b/.github/workflows/preview.yaml
--- a/.github/workflows/preview.yaml
+++ b/.github/workflows/preview.yaml
@@ -14,43 +14,43 @@ env:
   MONGODB_URI: ${{ secrets.MONGODB_URI }}
 
 jobs:
-  lint:
-    runs-on: ubuntu-latest
-    timeout-minutes: 10
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # lint:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 10
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18
-          cache: npm
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18
+  #         cache: npm
 
-      - name: Install dependencies
-        run: npm ci
+  #     - name: Install dependencies
+  #       run: npm ci
 
-      - name: Run Eslint
-        run: npm run lint
+  #     - name: Run Eslint
+  #       run: npm run lint
 
-  unit-tests:
-    runs-on: ubuntu-latest
-    timeout-minutes: 10
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # unit-tests:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 10
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18
-          cache: npm
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18
+  #         cache: npm
 
-      - name: Install dependencies
-        run: npm ci
+  #     - name: Install dependencies
+  #       run: npm ci
 
-      - name: Run Jest
-        run: npm run jest
+  #     - name: Run Jest
+  #       run: npm run jest
 
   e2e-tests:
     runs-on: ubuntu-latest
@@ -90,51 +90,56 @@ jobs:
       - run: ls -R cypress/snapshots
 
       - name: Run Cypress tests
-        run: npm run cy:test
+        run: npm run cy:test || echo "TESTS_FAILED=true" >> $GITHUB_ENV
         continue-on-error: true
 
       - name: Upload snapshots as new artifact
         uses: actions/upload-artifact@v4
+        if: always()
         with:
           name: cypress-snapshots-comparison-results
           path: cypress/snapshots
           retention-days: 30
 
-  preview-deployment:
-    runs-on: ubuntu-latest
-    timeout-minutes: 10
-    environment:
-      name: preview
-      url: ${{ steps.deploy.outputs.url }}
-    needs:
-      - lint
-      - unit-tests
-      - e2e-tests
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - name: Fail workflow if tests failed
+        if: env.TESTS_FAILED == 'true'
+        run: exit 1
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18
-          cache: npm
+  # preview-deployment:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 10
+  #   environment:
+  #     name: preview
+  #     url: ${{ steps.deploy.outputs.url }}
+  #   needs:
+  #     - lint
+  #     - unit-tests
+  #     - e2e-tests
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Install dependencies
-        run: npm ci
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18
+  #         cache: npm
 
-      - name: Install Vercel CLI
-        run: npm install --global vercel@latest
+  #     - name: Install dependencies
+  #       run: npm ci
 
-      - name: Pull Vercel Environment Information
-        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
+  #     - name: Install Vercel CLI
+  #       run: npm install --global vercel@latest
 
-      - name: Build Project Artifacts
-        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
+  #     - name: Pull Vercel Environment Information
+  #       run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
 
-      - name: Deploy Project Artifacts to Vercel
-        id: deploy
-        run: |
-          DEPLOY_URL=$(vercel deploy --prebuilt --token='${{ secrets.VERCEL_TOKEN }}')
-          echo "url=$DEPLOY_URL" >> $GITHUB_OUTPUT
-          echo "Preview URL: $DEPLOY_URL"
+  #     - name: Build Project Artifacts
+  #       run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
+
+  #     - name: Deploy Project Artifacts to Vercel
+  #       id: deploy
+  #       run: |
+  #         DEPLOY_URL=$(vercel deploy --prebuilt --token='${{ secrets.VERCEL_TOKEN }}')
+  #         echo "url=$DEPLOY_URL" >> $GITHUB_OUTPUT
+  #         echo "Preview URL: $DEPLOY_URL"
